export const AVAILABLE_BLOG_TAGS = [
  'Angular',
  'TypeScript',
  'NestJS',
  'PostgreSQL',
  'Docker',
  'DevOps',
  'Sécurité',
  'Architecture',
  'Tests',
  'SEO',
  'Parcours',
  'Reconversion',
  'Carrière',
  'Industrie',
  'Métallurgie',
  'Autodidacte',
  'Full-Stack',
  'Chiffrement',
  'Auto-hébergement',
  'CI/CD',
  'GreenTech',
] as const;
